/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MaprootImport } from './routes/map/__root'

// Create Virtual Routes

const MapImport = createFileRoute('/map')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const MapIndexLazyImport = createFileRoute('/map/')()
const MapMajorLazyImport = createFileRoute('/map/$major')()

// Create/Update Routes

const MaprootRoute = MaprootImport.update({
  id: '/__root',
  getParentRoute: () => MapRoute,
} as any)

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MapIndexLazyRoute = MapIndexLazyImport.update({
  path: '/',
  getParentRoute: () => MapRoute,
} as any).lazy(() => import('./routes/map/index.lazy').then((d) => d.Route))

const MapMajorLazyRoute = MapMajorLazyImport.update({
  path: '/$major',
  getParentRoute: () => MapRoute,
} as any).lazy(() => import('./routes/map/$major.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/map/__root': {
      preLoaderRoute: typeof MaprootImport
      parentRoute: typeof MapRoute
    }
    '/map/$major': {
      preLoaderRoute: typeof MapMajorLazyImport
      parentRoute: typeof MapImport
    }
    '/map/': {
      preLoaderRoute: typeof MapIndexLazyImport
      parentRoute: typeof MapImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  MapRoute.addChildren([MapMajorLazyRoute, MapIndexLazyRoute]),
])

/* prettier-ignore-end */
